### PR TITLE
The home page clone

### PR DESCRIPTION
**Pull request by ammarkandel**
Clone the home page of thenextweb.com using: 
- HTML
- CSS
   - flexbox
   - grid
   - Mediaquery

### CODE REVIEW

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 

Great job @ammarkandel you really impressed me with this clone :clap: :clap: :clap: :clap:, we can say it's almost identical :100: :+1:, but you still have to work :wrench: :hammer: :toolbox:  just on some minor changes to get your project approved :checkered_flag:. 

## Required changes:

- [x] make sure to give max-width to your page cause this is how it looks like in my 4k laptop:
image

- [x] Fix your breakpoint for tablet views, it should be 768 instead of 797:
image

- [x] In the latest news section the container of your article titles and desc are bigger than the container of the image, please give them the same size:
image

- [x] The white space on the right and left are not equal:
image

- [x] The tnw logo is not well positioned on small computer screens:
image

- [x] the stackpath logo should be in line with the text, please feel free to use the logo on the original page:
image

- [x] I have noticed that you didn't use Float at all in this project, it's one of the requirements can you please use it on the bottom section of your page where you have the social media logos just to prove that you know how to use it, thanks.

## Optional changes:

- [ ] use different images for different article

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_don't hesitate to contact me on slack if you have any questions or even if you needed help_

**Comment by ammarkandel** [comment]
Hi @elmejdki ,
 
about add max width for the page the footer and header will be not limited width but the other content will have max width ( the content between the header and footer )

**Comment by elmejdki** [comment]
Yes indeed, that what you need to do exactly.

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:



_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Pull request merged**
